// Survey table + field IDs in the Summer Intensives Airtable base.
// Generated by scripts/create_survey_tables.py.

export const SURVEY_BASE_ID = process.env.AIRTABLE_BASE_ID!;
export const APPLICATIONS_TABLE_ID =
  process.env.AIRTABLE_TABLE_ID || "tblzpCIOIsRpfJryh";

export const SURVEY = {
  intake: {
    tableId: "tblVi3jowYcdbu4bj",
    fields: {
      submissionId: "fldbuzFYa3NgymuiS",
      participant: "flds1gw0MYOjuXZhl",
      submittedAt: "fldZMZCBXlS3xWYN6",
      priorExposure: "fldIB3luUzsoMCAMk",
      counterfactual: "fldoTbsCJlA9MPLAu",
      knowledgeAis: "fld9401W8ep3XX9yQ",
      knowledgeEvals: "fld3IR2NEti49u8Q0",
      knowledgeFt: "fldGsuyL3r2JWZBzK",
      knowledgeMech: "fldIraYqUf8DtqWtb",
      fieldFit: "fldNFwpuKwL0aJqos",
      careerClarity: "fldjCqpGn43RbwjGj",
      belonging: "fld8fGkWAYHKDHtSU",
      selfEfficacy: "fldVuQU9tqFLvQmWR",
      hoursPerWeek: "fldW9oj2786IPXN2s",
      careerBucket: "fldDWuJ7vNtEWD6f1",
      careerBucketOther: "fldmYKHeG99AoZPsZ",
      dietaryRestrictions: "fldGsKJa34v9R3eJx",
      pronouns: "fldzN9aWGQ2WJUpTM",
      photoConsent: "fldSdQHnVmPBLD9vX",
      shirtSize: "fldTMupTV0hJyDSlv",
    },
  },
  pulse: {
    tableId: "tblR1zpLyNl0uvnrB",
    fields: {
      submissionId: "fldB8JUBN5SR4qEwq",
      participant: "fldrxYMV3e1RkkU2o",
      submittedAt: "fldqEpHjOFYbNdgv7",
      week: "fldIcDe2VEH2MzTMW",
      dayNps: "flddnBFn2vFmOLcbL",
      bestPart: "fldN3tf6ZwBDEolIR",
      whatChange: "fldd2ASSeJRhKJHpX",
      anythingElse: "fldpIGf0YYMcYuGn1",
      readings: "fld2e6AaT0mrN2Kdw",
      taFrequency: "fld7NW0V60rqT7yZG",
      notebookDifficulty: "fldbjZ94HTZoWvxB5",
    },
  },
  // Long-format: one row per activity rated, per participant, per week.
  pulseRatings: {
    tableId: "tbluGvhL0qVJQOMrI",
    fields: {
      submissionId: "fld3qpFOvsvCjWfa3",
      participant: "fldaaiPXB1faGXWME",
      submittedAt: "fld28bwtkW4Ue27sq",
      week: "fldfcGAqlmBO7TAgw",
      activity: "fldOZTKJq8NQA6lTm",
      rating: "fldvgaRu19iDKWHMv",
      reason: "fldm8UIPYf4eL4GLg",
    },
  },
  exit: {
    tableId: "tblRtd6U9JlpU4rNi",
    fields: {
      submissionId: "fldKoAK0astWB4vO1",
      participant: "fld4KBx8AIIkY0jr4",
      submittedAt: "fldEjRr9etVlWAAjk",
      knowledgeAis: "fld0X9gJBkAgyOPyT",
      knowledgeEvals: "fld16jTZ1yN1uYdwB",
      knowledgeFt: "fldEFryKs9uRkYG7C",
      knowledgeMech: "fldjIF4mFA7PISY95",
      fieldFit: "fld9MKS9m5oxM2o9I",
      careerClarity: "fldW9XBpLqqyx7rVR",
      belonging: "fldEhVbWHgyloypnH",
      selfEfficacy: "fldL22tk51dcmeHIz",
      canNameOrgs: "fldEEVsOsvFncCn23",
      orgsList: "fld9jyrmYgj4y1dOr",
      barriers: "fldjnAQMDCUjbwf9b",
      barriersOther: "flduu0B2R8xq8qIMj",
      careerBucket: "fld8dQ9JnjwvkzMZY",
      careerBucketOther: "fldqXWgE991MZClDL",
      commitment: "fldrF8zfEPZLsyBo2",
      stayInTouch: "fld0GvvGlELx2ByFA",
      favouriteParts: "fldXbgW3NUcFU82UH",
      favouritePartsOther: "fldunFYGxfcXE6kT8",
      mostValuableWeek: "fldDF9oBi0xHaG50X",
      whyMostValuable: "fldGlXBm8TuCGJL6v",
      doubleDownOn: "fldGT450H43seQNX8",
      cutOrChange: "fldLKeP4A9P2xtfUI",
      peopleToCallOut: "fld3ehnwavrVlGf13",
      programNps: "fld10yE6p649KRV2T",
      anythingElse: "fldl46kMU9gwNes9D",
      referrals: "fldF29wOSX1HqpzYQ",
      futureHelp: "fld4xrErSkGp2Xn4F",
      testimonial: "fldw3owoQTqt6PqYZ",
    },
  },
  followup: {
    tableId: "tbl3dpgcnDBjrtMOg",
    fields: {
      submissionId: "fldKcxbWIBFBsaADS",
      participant: "fldwEyvUSqcTj9KZA",
      submittedAt: "fldcWZL9P431s021s",
      hoursPerWeek: "fldSdjTx3SCgX83LQ",
      involvement: "fldTxHzst7k1j4AAR",
      fellowshipOrJob: "fld1FfBBHwnnmslMp",
      didYouDoIt: "fldG6bVIV7O4Raqc2",
      whatGotInTheWay: "fldb3d7R1m4qPkagx",
      fieldFit: "fld7PiNSKH7I4qbuV",
      careerClarity: "fldLaNHjEtYx6okeS",
      belonging: "fldN2jdo92ZqQusEY",
      selfEfficacy: "fldY5mQKwbpYU5Wgj",
      canNameOrgs: "fldJNozNdpNiUdEFi",
      orgsList: "fld0TbLIenoXMKZ36",
      barriers: "fldh7ird4kWqKU28L",
      barriersOther: "fldVbfVYE07nI340M",
      hindsightFeedback: "fldlzvhpN7cP5XpmO",
      stillInTouch: "fld6Po88ym2M0mbNY",
      referrals: "fldUXwC72B1e6TzUl",
      futureHelp: "fldjFAvQMCZ3fQ591",
    },
  },
} as const;

// The 5-point agreement scales are stored in Airtable as singleSelect label
// text (e.g. "Slightly agree"), not a number. The UI submits 1..5; convert it.
export const AGREEMENT_LABELS = [
  "Strongly disagree",
  "Slightly disagree",
  "Neutral",
  "Slightly agree",
  "Strongly agree",
] as const;

export function toAgreementLabel(
  v: number | null | undefined
): string | null {
  if (typeof v !== "number" || v < 1 || v > 5) return null;
  return AGREEMENT_LABELS[v - 1];
}

const PAT = process.env.AIRTABLE_PAT!;

export function airtableHeaders() {
  return {
    Authorization: `Bearer ${PAT}`,
    "Content-Type": "application/json",
  };
}

export type AirtableFields = Record<string, unknown>;

export async function createAirtableRecord(
  tableId: string,
  fields: AirtableFields
) {
  const res = await fetch(
    `https://api.airtable.com/v0/${SURVEY_BASE_ID}/${tableId}`,
    {
      method: "POST",
      headers: airtableHeaders(),
      body: JSON.stringify({ records: [{ fields }] }),
    }
  );
  if (!res.ok) {
    const detail = await res.text();
    console.error("Airtable create error:", res.status, detail);
    throw new Error("Could not save your survey response. Please try again.");
  }
  return res.json();
}

// Create many records in one table (Airtable caps at 10 per request; chunked).
export async function createAirtableRecords(
  tableId: string,
  records: AirtableFields[]
) {
  for (let i = 0; i < records.length; i += 10) {
    const chunk = records.slice(i, i + 10).map((fields) => ({ fields }));
    const res = await fetch(
      `https://api.airtable.com/v0/${SURVEY_BASE_ID}/${tableId}`,
      {
        method: "POST",
        headers: airtableHeaders(),
        body: JSON.stringify({ records: chunk }),
      }
    );
    if (!res.ok) {
      const detail = await res.text();
      console.error("Airtable batch create error:", res.status, detail);
      throw new Error("Could not save your survey response. Please try again.");
    }
  }
}

export type Participant = {
  id: string;
  name: string;
  cohort?: string;
};

export async function fetchConfirmedParticipants(): Promise<Participant[]> {
  const url = new URL(
    `https://api.airtable.com/v0/${SURVEY_BASE_ID}/${APPLICATIONS_TABLE_ID}`
  );
  url.searchParams.set("pageSize", "100");
  url.searchParams.append("fields[]", "Full Name");
  url.searchParams.append("fields[]", "cohort");
  url.searchParams.append("fields[]", "Acceptance Status");
  url.searchParams.set(
    "filterByFormula",
    "{Acceptance Status} = 'Confirmed'"
  );

  const all: Participant[] = [];
  let offset: string | undefined;
  do {
    const u = new URL(url.toString());
    if (offset) u.searchParams.set("offset", offset);
    const res = await fetch(u.toString(), { headers: airtableHeaders() });
    if (!res.ok) {
      const detail = await res.text();
      console.error("Airtable participant lookup error:", res.status, detail);
      throw new Error("Could not load participant list.");
    }
    const data = (await res.json()) as {
      records: Array<{
        id: string;
        fields: { "Full Name"?: string; cohort?: string };
      }>;
      offset?: string;
    };
    for (const r of data.records) {
      const name = (r.fields["Full Name"] || "").trim();
      if (!name) continue;
      all.push({ id: r.id, name, cohort: r.fields.cohort });
    }
    offset = data.offset;
  } while (offset);

  all.sort((a, b) => a.name.localeCompare(b.name));
  return all;
}

// Fetch the most recent record from a survey table for a given participant.
// Returns the raw fields object keyed by field NAME (Airtable returns names by default).
export async function fetchLatestSurveyRecord(
  tableId: string,
  participantFieldId: string,
  participantRecordId: string
): Promise<Record<string, unknown> | null> {
  const url = new URL(
    `https://api.airtable.com/v0/${SURVEY_BASE_ID}/${tableId}`
  );
  url.searchParams.set("pageSize", "100");
  url.searchParams.set("returnFieldsByFieldId", "true");
  // Survey tables stay small; fetch + filter client-side rather than building a
  // FIND() formula against a linked-record column.
  const res = await fetch(url.toString(), { headers: airtableHeaders() });
  if (!res.ok) {
    const detail = await res.text();
    console.error("Airtable prefill lookup error:", res.status, detail);
    throw new Error("Could not load prefill data.");
  }
  const data = (await res.json()) as {
    records: Array<{ id: string; createdTime: string; fields: Record<string, unknown> }>;
  };
  const matching = data.records
    .filter((r) => {
      const v = r.fields[participantFieldId];
      return Array.isArray(v) && v.includes(participantRecordId);
    })
    .sort((a, b) => b.createdTime.localeCompare(a.createdTime));
  return matching[0]?.fields || null;
}

export function buildSubmissionId(participantName: string) {
  const date = new Date().toISOString().slice(0, 19).replace("T", " ");
  return `${participantName} - ${date}`;
}
